### ISSUE TITLE
Module Todo: Newsletter Scrapper

### ISSUE THREAD

**Issue by stryker2k2** [blacklanternsecurity/bbot#1056]
### Description:
- Create a new module called 'newsletters' that will scrap the websites (or recursive websites, thanks to BBOT's sub-domain enumeration) looking for the presence of an 'email type' that also contains a 'placeholder'. The combination of these two HTML items usually signify the presence of an "Enter Your Email Here" type Newsletter Subscription service. This module could be used to find newsletters for a future email bombing attack and/or find user-input fields that could be be susceptible to overflows or injections.

### Module Development Checklist:
- [x]  Watch for 'URL' events and outputs 'NEWLETTER' event
- [x]  Perform a GET Request on received 'URL' events
- [x]  Scrap HTML for Newsletter Submission text box with Placeholder Text
- [x]  Emit a Boolean Event to signal if Newsletter Submission box is present
- [x]  Have automated tests to ensure module functionality
- [x]  Create PULL Request and fix peer-review issues

![Image](https://github.com/blacklanternsecurity/bbot/assets/18358246/55e06431-2df1-481f-889f-ef9299b37c3b)

**Comment by stryker2k2** [comment]
Update: 
I have a good working newsletter module up and running (see screenshot). It is looking good. What I want to do next is:

- [x] Add Tests
- [x] Determine if I must run `-m httpx newsletters` together... or if I can make newsletters dependent on httpx natively
- [x] Run against many known 'Newsletter' website to verify
- [x] Add logic to discover all forms of Newsletter Submissions, as required
- [x] View how the `[NEWSLETTER]` events look in NEO4J
- [x] Create Pull Request

![Image](https://github.com/blacklanternsecurity/bbot/assets/18358246/445bcd0d-497f-48d0-93d1-e98921a0a344)

**Comment by stryker2k2** [comment]
> Determine if I must run -m httpx newsletters together... or if I can make newsletters dependent on httpx natively


As the moment, if there are multiple feasible recursive dependencies (ex: httpx & gowitness), BBOT will ask the Operator to make that decision via the `-m` argument.

See https://github.com/blacklanternsecurity/bbot/discussions/746 for more information

**Comment by stryker2k2** [comment]
https://github.com/blacklanternsecurity/bbot/pull/1072 has been merged into DEV Branch. Closing out ticket/issue.
